/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:a987cdb2-fa71-470a-b32b-d832d7176cc7",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_IQiH8WK8M",
    "aws_user_pools_web_client_id": "2cte0s24uv33kfl21a1tqr03ca",
    "oauth": {}
};


export default awsmobile;
