/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:36acad34-c33c-4a80-92d5-aeb4ad9b4622",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_9IUxsHqEH",
    "aws_user_pools_web_client_id": "58pgscgdcmokft47pddndtahbs",
    "oauth": {}
};


export default awsmobile;
